deployments:
  BookEcommerce.Web:
    path: /mnt/c/MigrationGithubActions/BookEcommerce.Web
  BooksEcommerce.Services.ProductAPI:
    path: /mnt/c/MigrationGithubActions/ProductAPI
  BooksEcommerce.Services.UserAPI:
    path: /mnt/c/MigrationGithubActions/UserAPI
