name: CI Pipeline

# Trigger the pipeline on push for every branch
on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  build:
    runs-on: self-hosted  # Your self-hosted runner

    steps:

      # Print the branch name
      - name: Set branch name environment variable
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch name stored: $BRANCH_NAME"

      # Trigger Jenkins job with branch name as parameter, skipping SSL verification
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://192.168.98.75:8080/job/template1/job/Qualite/buildWithParameters" \
               --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
               --data-urlencode "BRANCH_NAME=${{ env.BRANCH_NAME }}"
          
